import requests

UNIVERSITIES = [
    {"title": "Chongqing Medical University", "title_cn": "重庆医科大学", "city": "Chongqing City", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Chongqing_Medical_University.jpg/640px-Chongqing_Medical_University.jpg", "fee_chinese_language": "16,000 RMB", "fee_bachelor_cn": "30,000 RMB", "fee_bachelor_en": "30,000 RMB", "fee_dormitory_single": "9,600 RMB", "fee_dormitory_double": "4,800 RMB"},
    {"title": "Chongqing University of Posts and Telecommunications", "title_cn": "重庆邮电大学", "city": "Chongqing City", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/CQUPT.jpg/640px-CQUPT.jpg", "fee_chinese_language": "15,000 RMB", "fee_bachelor_cn": "15,000 RMB", "fee_bachelor_en": "35,000 RMB", "fee_dormitory_single": "8,400 RMB", "fee_dormitory_double": "4,200 RMB"},
    {"title": "Ningbo University", "title_cn": "宁波大学", "city": "Ningbo City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ningbo_University.jpg/640px-Ningbo_University.jpg", "fee_chinese_language": "16,000 RMB", "fee_bachelor_cn": "20,000 RMB", "fee_bachelor_en": "18,000-38,000 RMB", "fee_dormitory_single": "14,400 RMB", "fee_dormitory_double": "10,800 RMB"},
    {"title": "Wenzhou Medical University", "title_cn": "温州医科大学", "city": "Wenzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wenzhou_Medical_University.jpg/640px-Wenzhou_Medical_University.jpg", "fee_chinese_language": None, "fee_bachelor_cn": None, "fee_bachelor_en": "20,000-33,000 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "4,400 RMB"},
    {"title": "Zhejiang Normal University", "title_cn": "浙江师范大学", "city": "Jinhua City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Zhejiang_Normal_University.jpg/640px-Zhejiang_Normal_University.jpg", "fee_chinese_language": "14,000 RMB", "fee_bachelor_cn": "18,000 RMB", "fee_bachelor_en": "18,000 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "5,400-7,200 RMB"},
    {"title": "Hangzhou Normal University", "title_cn": "杭州师范大学", "city": "Hangzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Hangzhou_Normal_University.jpg/640px-Hangzhou_Normal_University.jpg", "fee_chinese_language": "15,000 RMB", "fee_bachelor_cn": "18,000-20,000 RMB", "fee_bachelor_en": "20,000-25,000 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "7,000-14,000 RMB"},
    {"title": "Zhejiang Gongshang University", "title_cn": "浙江工商大学", "city": "Hangzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Zhejiang_Gongshang_University.jpg/640px-Zhejiang_Gongshang_University.jpg", "fee_chinese_language": "14,000 RMB", "fee_bachelor_cn": "18,000-24,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "7,800 RMB"},
    {"title": "Zhejiang University of Technology", "title_cn": "浙江工业大学", "city": "Hangzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Zhejiang_University_of_Technology.jpg/640px-Zhejiang_University_of_Technology.jpg", "fee_chinese_language": "14,000 RMB", "fee_bachelor_cn": "16,200 RMB", "fee_bachelor_en": "18,800 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "3,500 RMB"},
    {"title": "Zhejiang A&F University", "title_cn": "浙江农林大学", "city": "Hangzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Zhejiang_AF_University.jpg/640px-Zhejiang_AF_University.jpg", "fee_chinese_language": "14,000 RMB", "fee_bachelor_cn": "20,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "8,400-12,000 RMB"},
    {"title": "Hangzhou Dianzi University", "title_cn": "杭州电子科技大学", "city": "Hangzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Hangzhou_Dianzi_University.jpg/640px-Hangzhou_Dianzi_University.jpg", "fee_chinese_language": "16,000 RMB", "fee_bachelor_cn": "18,000-20,000 RMB", "fee_bachelor_en": "18,000-20,000 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "5,400 RMB"},
    {"title": "Zhejiang University of Finance and Economics", "title_cn": "浙江财经大学", "city": "Hangzhou City, Zhejiang Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Zhejiang_University_of_Finance_and_Economics.jpg/640px-Zhejiang_University_of_Finance_and_Economics.jpg", "fee_chinese_language": "17,000 RMB", "fee_bachelor_cn": "19,000 RMB", "fee_bachelor_en": "19,000 RMB", "fee_dormitory_single": "9,000 RMB", "fee_dormitory_double": "5,000 RMB"},
    {"title": "Sichuan University", "title_cn": "四川大学", "city": "Chengdu City, Sichuan Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Sichuan_University_Wangjiang_Campus.jpg/640px-Sichuan_University_Wangjiang_Campus.jpg", "fee_chinese_language": "16,500 RMB", "fee_bachelor_cn": "17,500-45,000 RMB", "fee_bachelor_en": "17,500-45,000 RMB", "fee_dormitory_single": "18,000-18,720 RMB", "fee_dormitory_double": "12,960-17,280 RMB"},
    {"title": "East China University of Science and Technology", "title_cn": "华东理工大学", "city": "Shanghai City", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/ECUST.jpg/640px-ECUST.jpg", "fee_chinese_language": "19,600 RMB", "fee_bachelor_cn": "22,000-30,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "28,800-39,600 RMB"},
    {"title": "Shanghai University of Finance and Economics", "title_cn": "上海财经大学", "city": "Shanghai City", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/SUFE.jpg/640px-SUFE.jpg", "fee_chinese_language": "18,000 RMB", "fee_bachelor_cn": "30,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": "28,800-36,000 RMB", "fee_dormitory_double": "21,600 RMB"},
    {"title": "Shanghai University of Traditional Chinese Medicine", "title_cn": "上海中医药大学", "city": "Shanghai City", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/SHUTCM.jpg/640px-SHUTCM.jpg", "fee_chinese_language": "19,000 RMB", "fee_bachelor_cn": "20,000-28,000 RMB", "fee_bachelor_en": "20,000-28,000 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "4,800-16,800 RMB"},
    {"title": "Northwest University", "title_cn": "西北大学", "city": "Xi'an, Shaanxi Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Northwest_University_China.jpg/640px-Northwest_University_China.jpg", "fee_chinese_language": "15,000 RMB", "fee_bachelor_cn": "15,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "7,500 RMB"},
    {"title": "Shaanxi Normal University", "title_cn": "陕西师范大学", "city": "Xi'an, Shaanxi Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9g/Shaanxi_Normal_University.jpg/640px-Shaanxi_Normal_University.jpg", "fee_chinese_language": "15,000 RMB", "fee_bachelor_cn": "16,500-32,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "3,500-9,000 RMB"},
    {"title": "Chang'an University", "title_cn": "长安大学", "city": "Xi'an, Shaanxi Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Changan_University.jpg/640px-Changan_University.jpg", "fee_chinese_language": "14,000 RMB", "fee_bachelor_cn": "16,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "7,200 RMB"},
    {"title": "Xi'an University of Architecture and Technology", "title_cn": "西安建筑科技大学", "city": "Xi'an, Shaanxi Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2g/XAUAT.jpg/640px-XAUAT.jpg", "fee_chinese_language": "20,000 RMB", "fee_bachelor_cn": "25,000 RMB", "fee_bachelor_en": None, "fee_dormitory_single": None, "fee_dormitory_double": "9,600 RMB"},
    {"title": "Xidian University", "title_cn": "西安电子科技大学", "city": "Xi'an, Shaanxi Province", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3g/Xidian_University.jpg/640px-Xidian_University.jpg", "fee_chinese_language": "15,000 RMB", "fee_bachelor_cn": "20,000 RMB", "fee_bachelor_en": "22,000 RMB", "fee_dormitory_single": None, "fee_dormitory_double": "7,200 RMB"},
]

for uni in UNIVERSITIES:
    response = requests.post("http://127.0.0.1:8001/universities/", json=uni)
    if response.status_code == 200:
        print(f"✅ {uni['title']}")
    else:
        print(f"❌ {uni['title']} — {response.text}")
